name: numpy_to_jax
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=4.2.0
  - appnope=0.1.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.7
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - comm=0.2.1
  - cryptography=42.0.5
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - expat=2.5.0
  - idna=3.4
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - ipykernel=6.28.0
  - ipython=8.20.0
  - jedi=0.18.1
  - jinja2=3.1.3
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=2.10.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.11
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - libcxx=14.0.6
  - libffi=3.4.4
  - libgfortran
  - libgfortran5
  - libopenblas=0.3.21
  - libsodium=1.0.18
  - llvm-openmp=14.0.6
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - notebook=7.0.8
  - notebook-shim=0.2.3
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.0.13
  - overrides=7.4.0
  - packaging=23.2
  - pandas=2.2.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=3.10.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=24.0.0
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - readline=8.2
  - referencing=0.30.2
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - scipy=1.13.1
  - send2trash=1.8.2
  - setuptools=68.2.2
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.2.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.3.3
  - traitlets=5.7.1
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - tzdata=2024a
  - urllib3=2.1.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.41.2
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - arrow==1.3.0
      - astunparse==1.6.3
      - contourpy==1.2.1
      - cycler==0.12.1
      - filelock==3.14.0
      - flatbuffers==24.3.25
      - fonttools==4.51.0
      - fqdn==1.5.1
      - fsspec==2024.5.0
      - gast==0.5.4
      - google-pasta==0.2.0
      - grpcio==1.64.0
      - gviz-api==1.10.0
      - h5py==3.11.0
      - ipywidgets==8.1.2
      - isoduration==20.11.0
      - jax==0.4.26
      - jaxlib==0.4.26
      - jsonpointer==2.4
      - jupyter==1.0.0
      - jupyter-console==6.6.3
      - jupyterlab-widgets==3.0.10
      - keras==3.3.3
      - kiwisolver==1.4.5
      - lab==8.1
      - libclang==18.1.1
      - markdown==3.6
      - markdown-it-py==3.0.0
      - matplotlib==3.8.4
      - mdurl==0.1.2
      - ml-dtypes==0.3.2
      - mpmath==1.3.0
      - namex==0.0.8
      - networkx==3.3
      - opt-einsum==3.3.0
      - optree==0.11.0
      - pillow==10.3.0
      - protobuf==4.25.3
      - pyparsing==3.1.2
      - qtconsole==5.5.1
      - qtpy==2.4.1
      - rich==13.7.1
      - scipy==1.13.0
      - scikit-learn==1.2.2
      - simplejson==3.19.2
      - sympy==1.12
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorboard-plugin-profile==2.15.1
      - tensorflow==2.16.1
      - termcolor==2.4.0
      - torch==2.3.0
      - torchvision==0.18.0
      - tqdm==4.66.2
      - txt2tags==3.9
      - types-python-dateutil==2.9.0.20240316
      - uri-template==1.3.0
      - webcolors==1.13
      - werkzeug==3.0.3
      - widgetsnbextension==4.0.10
      - wrapt==1.16.0
